# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
stages:
- test
- deploy

test:
  image: node:8.11-alpine
  stage: test
  tags:
    - k8s
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - yarn install
    - yarn test-coverage

deploy:
  image: node:8.11-alpine
  stage: deploy
  only:
  - master@lalamove/lalamove-ui
  environment:
    name: storybook
    url: https://ui.lalamove.com/storybook/index.html
  script:
    - apk -v --update add python py-pip
    - pip install awscli --upgrade
    - yarn install
    - yarn storybook:build
    - AWS_ACCESS_KEY_ID=AKIAJKFWPBSAEI2FFBRQ AWS_SECRET_ACCESS_KEY=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 aws s3 cp .out s3://lalamove-ui/storybook --recursive
    - AWS_ACCESS_KEY_ID=AKIAJKFWPBSAEI2FFBRQ AWS_SECRET_ACCESS_KEY=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 aws s3 ls s3://lalamove-ui/storybook --recursive
    - echo "Upload completed"

