# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
stages:
- test
- deploy

test:
  image: node:8.11-alpine
  stage: test
  tags:
    - k8s
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - yarn install
    - yarn test-coverage

deploy:
  image: node:8.11-alpine
  stage: deploy
  only:
  - master@lalamove/lalamove-ui
  environment:
    name: storybook
    url: https://ui.lalamove.com/storybook
  script:
    - apk -v --update add python py-pip
    - pip install awscli --upgrade
    - yarn install
    - yarn storybook:build
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws s3 cp .out $S3_URL/storybook --recursive
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws s3 ls $S3_URL/storybook --recursive
    - echo "Upload completed"

